# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='division',
            field=models.CharField(default='\u6a39', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tree',
            name='type',
            field=models.CharField(default='\u6a39', max_length=20),
            preserve_default=False,
        ),
    ]
