# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160820_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
