# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tree_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='age',
            field=models.IntegerField(default=-1),
        ),
    ]
